services:
  - type: web
    name: trampou-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: trampou-db
          property: connectionString

databases:
  - name: trampou-db
    databaseName: trampou
    user: trampou_user
